### ISSUE TITLE
Redirect un-excellent HTTP requests to HTTPS

### ISSUE THREAD

**Issue by ioistired** [excellentorg/excellentrepo#3]
Some visitors use the less excellent form of link to your website, and taint its excellent-ness by visiting http://anexcellent.website. I humbly request that you redirect these well-meaning visitors to the HTTPS version, and add HSTS so that un-excellent TLAs cannot know what these visitors' "excellentPhrase" is.

I seem to recall you using the excellent NearlyFreeSpeech.NET hosting service before switching to CloudFlare. Is that still the case? If so, you don't need CloudFlare for TLS. Simply run `tls-setup.sh` and you're done. A task will be set up to auto-renew the certificates, and you can set up a redirect and an HSTS header there. If you don't use NFSN, forgive me, my memory is not so excellent these days.

**Comment by Skaty** [comment]
The website has excellent TLS set up on NFSN using LetsEncrypt. Unfortunately, I overlooked the force/redirect HTTPS + HSTS part, as I moved the DNS over to CloudFlare to ensure that the excellent high-resolution assets do not eat up too much bandwidth in NFSN. This is clearly not excellent.

Anyways, I've resolved this issue in a bid to maintain the excellent-ness of this excellent website. Now it's harder for any malicious entity to be able to deface or otherwise make this excellent website unexcellent through the use of MITM attacks.
